import { PRODUCTS } from './catalog.js';
import { freshState, handleMessage, summary, recommend } from './chat-engine.js';

const $=id=>document.getElementById(id);
const eur=n=>Number(n||0).toLocaleString('sl-SI',{style:'currency',currency:'EUR'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sessionKey='ed_session_id';
const sessionId=localStorage.getItem(sessionKey)||crypto.randomUUID();
localStorage.setItem(sessionKey,sessionId);
let state=freshState();
let cart=JSON.parse(localStorage.getItem('ed_cart')||'[]');
let history=[];
let currentRecs=[];

function save(){localStorage.setItem('ed_cart',JSON.stringify(cart));}
function toast(t){if(!$('toast'))return;$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function renderCart(){if($('cartCount'))$('cartCount').textContent=cart.length;if($('cartItems'))$('cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><span>${esc(p.name)}</span><b>${eur(p.price)}</b><button data-remove="${i}" aria-label="Odstrani">×</button></div>`).join(''):'<p>Košarica je prazna.</p>';if($('cartTotal'))$('cartTotal').textContent=eur(cart.reduce((a,p)=>a+Number(p.price||0),0));}
function bubble(t,who='bot',meta=''){const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=`<div>${String(t||'').replace(/\n/g,'<br>')}</div>${meta?`<small class="msg-meta">${esc(meta)}</small>`:''}`;$('chatMessages').appendChild(d);$('chatMessages').scrollTop=$('chatMessages').scrollHeight;}
function typing(on){$('typing')?.classList.toggle('hidden',!on)}
function productIcon(p){return p.category==='Svetila'||p.category==='Žarnice'?'💡':p.category==='Vtičnice'?'🔌':p.category==='Zaščita'?'⚡':p.category==='Kabli'?'🧵':'▣'}
function productCard(p,i){return `<article class="rec-card"><div class="rec-art">${productIcon(p)}</div><div class="rec-body"><div class="rec-top"><span class="tag">${esc(p.category)}</span><strong>${eur(p.price)}${p.unit?` / ${esc(p.unit)}`:''}</strong></div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'')}</p><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}</div><div class="rec-actions"><button class="dark-btn" data-choose="${p.id}">Izberi</button><button class="link-btn" data-detail="${p.id}">Zakaj ta izdelek?</button></div></div></article>`}
function showRecs(ps,reason=''){currentRecs=(ps||[]).filter(Boolean).slice(0,3);const el=$('recommendations');if(!el)return;el.innerHTML=currentRecs.length?`<div class="rec-head"><div><b>Predlagane možnosti</b>${reason?`<span>${esc(reason)}</span>`:''}</div><span>${currentRecs.length} ${currentRecs.length===1?'možnost':'možnosti'}</span></div>${currentRecs.map(productCard).join('')}`:'';}
function update(){const safety=state.safety?' · ⚠️ varnost':'';if($('state'))$('state').textContent=`V10 · ${state.step} · ${state.intent||'brez kategorije'}${state.location?' · '+state.location:''}${safety}`;renderDebug();}
function renderDebug(){if(!$('debugPanel'))return;const rows={sessionId,step:state.step,intent:state.intent,space:state.space,area:state.area,mounting:state.mounting,budget:state.budget,location:state.location,service:state.service,safety:state.safety,confidence:state.confidence};$('debugPanel').textContent=JSON.stringify(rows,null,2);}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;cart.push(p);save();renderCart();toast(`${p.name} je dodan v košarico.`)}
function chooseProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;state.selected=p;addToCart(id);showRecs([]);if(state.service&&state.location){state.step='lead';bubble(`Odlično. Izbral sem <b>${esc(p.name)}</b> za <b>${eur(p.price)}</b> in ga dodal v košarico.<br><br>Imate tudi <b>${esc(state.service.toLowerCase())}</b> v <b>${esc(state.location)}</b>. Lahko pripravim povpraševanje.`)}else{state.step='afterProduct';bubble(`Odlično. <b>${esc(p.name)}</b> je dodan v košarico.<br><br>Želite tudi pomoč električarja oziroma montažo?`)}update()}
function showDetail(id){const p=PRODUCTS.find(x=>x.id===id);if(!p||!$('productModal'))return;$('productModalTitle').textContent=p.name;$('productModalBody').innerHTML=`<div class="detail-icon">${productIcon(p)}</div><div class="detail-copy"><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}${p.diameter?`<span>Ø ${esc(p.diameter)}</span>`:''}</div><p>${esc(p.desc||'')}</p><h3>Zakaj je lahko primeren?</h3><p>${p.category==='Svetila'?'Upošteva osnovne parametre, ki ste jih navedli. Pri kopalnici je treba poleg IP preveriti tudi konkretno mesto in izvedbo.':p.category==='Zaščita'?'Gre za zaščitni element, vendar pravilnega tipa in nazivne vrednosti ni varno določiti brez podatkov o tokokrogu.':'Izdelek je izbran glede na trenutno zbrane podatke in lastnosti kataloga.'}</p><button class="dark-btn" data-modal-add="${p.id}">Dodaj v košarico · ${eur(p.price)}</button></div>`;$('productModal').classList.remove('hidden')}
function closeDetail(){$('productModal')?.classList.add('hidden')}
async function aiSend(){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history,state,sessionId})});if(!r.ok)throw new Error('AI unavailable');return r.json()}
async function send(text){text=text.trim();if(!text)return;bubble(esc(text),'user');history.push({role:'user',content:text});typing(true);
  if(['offer','lead','afterProduct'].includes(state.step)){const local=handleMessage(text,state);if(local.type==='selected'){typing(false);chooseProduct(local.product.id);return}if(local.type==='lead'){typing(false);prepareLead();return}if(local.type==='serviceAsk'){typing(false);bubble('Seveda. Za povpraševanje potrebujem še kontakt in lahko preverimo lokacijo.');showLead();update();return}if(local.type==='done'){typing(false);bubble('V redu. Ko boste želeli, lahko nadaljujemo.');update();return}}
  try{const ai=await aiSend();Object.assign(state,ai.statePatch||{});if(ai.safetyLevel==='electrician_required'){state.safety=true;state.safetyReason=state.safetyReason||'varnostno tveganje'}
    typing(false);if(ai.productIds?.length){const ps=ai.productIds.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean);showRecs(ps,ai.reasoningSummary);state.step='offer'}else if(ai.statePatch?.step==='offer'){showRecs(recommend(state),ai.reasoningSummary);state.step='offer'}
    bubble(esc(ai.reply||'').replace(/\n/g,'<br>'), 'bot', ai.safetyLevel==='electrician_required'?'Priporočljiv strokovni pregled':'AI svetovalec');history.push({role:'assistant',content:ai.reply||''});if(ai.nextQuestion&&!ai.reply?.includes(ai.nextQuestion)){}update();
  }catch(e){typing(false);const local=handleMessage(text,state);if(local.type==='question')bubble(esc(local.text));else if(local.type==='recommend'){bubble('Razumem. Na podlagi zbranih podatkov predlagam naslednje možnosti.');showRecs(local.products)}else if(local.type==='selected')chooseProduct(local.product.id);else if(local.type==='safety')bubble(esc(local.text));else if(local.type==='serviceLead'){state.step='lead';bubble(`Zabeležil sem potrebo po električarju v kraju <b>${esc(state.location)}</b>.<br><br>Pripravimo povpraševanje?`)}else bubble('AI trenutno ni dosegljiv. Opišite težavo še malo bolj konkretno in poskusil bom pomagati tudi lokalno.');update()}
}
function showLead(){if($('leadBox'))$('leadBox').classList.remove('hidden');if($('leadLocation'))$('leadLocation').value=state.location||'';$('leadBox')?.scrollIntoView({behavior:'smooth',block:'center'});$('leadNote').value=summary(state).join('\n')}
function prepareLead(){showLead();if(state.selected)$('leadNote').value=summary(state).join('\n');bubble(`<b>Povpraševanje je pripravljeno.</b><br><br>${summary(state).map(esc).join('<br>')}<br><br>Izpolnite kontaktne podatke in pošljite povpraševanje.`);update()}
async function submitLead(e){e.preventDefault();const btn=$('leadSubmit');btn.disabled=true;btn.textContent='Pošiljam …';const payload={name:$('leadName').value,email:$('leadEmail').value,phone:$('leadPhone').value,location:$('leadLocation')?.value||state.location||'',service:state.service||'',note:$('leadNote').value,summary:summary(state),sessionId};try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Napaka');$('leadResult').hidden=false;$('leadResult').innerHTML=`<b>✓ Povpraševanje poslano.</b><br>Številka: <strong>${esc(d.id)}</strong>`;state.step='completed';update();toast('Povpraševanje je sprejeto.');}catch(err){$('leadResult').hidden=false;$('leadResult').textContent=err.message||'Povpraševanja ni bilo mogoče poslati.'}finally{btn.disabled=false;btn.textContent='Pošlji povpraševanje'}}
function reset(){state=freshState();history=[];currentRecs=[];if($('chatMessages'))$('chatMessages').innerHTML='';showRecs([]);if($('leadBox'))$('leadBox').classList.add('hidden');if($('leadResult')){$('leadResult').hidden=true;$('leadResult').textContent=''};bubble('Pozdravljeni! Sem <b>ElektroDom Expert</b>.<br>Opišite problem ali povejte, kaj potrebujete. Lahko napišete vse v enem stavku — najprej bom razumel situacijo, nato predlagal naslednji korak.');update()}
function startExample(t){$('chatInput').value=t;$('chatInput').focus()}
function openCart(){$('cartModal')?.classList.remove('hidden');renderCart()}function closeCart(){$('cartModal')?.classList.add('hidden')}
function removeCart(i){cart.splice(i,1);save();renderCart()}
function renderProducts(){const grid=$('productGrid');if(!grid)return;const q=($('productSearch')?.value||'').toLowerCase().trim();const cat=$('productCategory')?.value||'';grid.innerHTML=PRODUCTS.filter(p=>(!q||`${p.name} ${p.category} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q))&&(!cat||p.category===cat)).map(p=>`<article class="product"><div class="product-icon">${productIcon(p)}</div><div class="tag">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}</div><div class="product-bottom"><strong>${eur(p.price)}${p.unit?` / ${esc(p.unit)}`:''}</strong><button data-add="${p.id}">Dodaj</button></div><button class="product-link" data-detail="${p.id}">Podrobnosti →</button></article>`).join('')||'<p>Ni zadetkov.</p>'}
function setup(){
  document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){addToCart(+add.dataset.add);return}const choose=e.target.closest('[data-choose]');if(choose){chooseProduct(+choose.dataset.choose);return}const detail=e.target.closest('[data-detail]');if(detail){showDetail(+detail.dataset.detail);return}const rem=e.target.closest('[data-remove]');if(rem){removeCart(+rem.dataset.remove);return}const modalAdd=e.target.closest('[data-modal-add]');if(modalAdd){addToCart(+modalAdd.dataset.modalAdd);closeDetail();return}});
  if($('chatForm'))$('chatForm').addEventListener('submit',e=>{e.preventDefault();const t=$('chatInput').value;$('chatInput').value='';send(t)});
  if($('resetChat'))$('resetChat').addEventListener('click',reset);if($('cartButton'))$('cartButton').addEventListener('click',openCart);if($('closeCart'))$('closeCart').addEventListener('click',closeCart);if($('closeProductModal'))$('closeProductModal').addEventListener('click',closeDetail);if($('productSearch'))$('productSearch').addEventListener('input',renderProducts);if($('productCategory'))$('productCategory').addEventListener('change',renderProducts);if($('leadForm'))$('leadForm').addEventListener('submit',submitLead);
  document.querySelectorAll('.example-btn').forEach(b=>b.addEventListener('click',()=>startExample(b.dataset.example)));
  renderCart();renderProducts();if(new URLSearchParams(location.search).get('debug')==='1')$('debugPanel')?.classList.remove('hidden');if($('chatMessages'))reset();
}
window.addToCart=addToCart;window.chooseProduct=chooseProduct;window.openCart=openCart;window.closeCart=closeCart;window.startExample=startExample;window.resetChat=reset;
setup();
