import { PRODUCTS } from './catalog.js';
import { freshState, handleMessage, summary, recommend } from './chat-engine.js';
const $=id=>document.getElementById(id);
const eur=n=>Number(n||0).toLocaleString('sl-SI',{style:'currency',currency:'EUR'});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sessionKey='ed_session_id';
const sessionId=localStorage.getItem(sessionKey)||(crypto.randomUUID?crypto.randomUUID():String(Date.now()));
localStorage.setItem(sessionKey,sessionId);
let state=freshState(); let cart=JSON.parse(localStorage.getItem('ed_cart')||'[]'); let history=[]; let currentRecs=[];
function save(){localStorage.setItem('ed_cart',JSON.stringify(cart))}
function toast(t){if(!$('toast'))return;$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function renderCart(){if($('cartCount'))$('cartCount').textContent=cart.length;if($('cartItems'))$('cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><span>${esc(p.name)}</span><b>${eur(p.price)}</b><button data-remove="${i}" aria-label="Odstrani">×</button></div>`).join(''):'<p>Košarica je prazna.</p>';if($('cartTotal'))$('cartTotal').textContent=eur(cart.reduce((a,p)=>a+Number(p.price||0),0))}
function openCart(){$('cartModal')?.classList.remove('hidden');renderCart()}function closeCart(){$('cartModal')?.classList.add('hidden')}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;cart.push(p);save();renderCart();toast(`${p.name} je dodan v košarico.`)}
function removeCart(i){cart.splice(i,1);save();renderCart()}
function productIcon(p){return p.category==='Svetila'||p.category==='Žarnice'?'💡':p.category==='Vtičnice'?'🔌':p.category==='Zaščita'?'⚡':p.category==='Kabli'?'🧵':p.category==='Stikala'?'◉':'▣'}
function productCard(p){return `<article class="rec-card"><div class="rec-art">${productIcon(p)}</div><div class="rec-body"><div class="rec-top"><span class="tag">${esc(p.category)}</span><strong>${eur(p.price)}${p.unit?` / ${esc(p.unit)}`:''}</strong></div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'')}</p><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}</div><div class="rec-actions"><button class="dark-btn" data-choose="${p.id}">Izberi</button><button class="link-btn" data-detail="${p.id}">Zakaj ta izdelek?</button></div></div></article>`}
function showRecs(ps,reason=''){currentRecs=(ps||[]).filter(Boolean).slice(0,3);const el=$('recommendations');if(!el)return;el.innerHTML=currentRecs.length?`<div class="rec-head"><div><b>Priporočeni izdelki</b>${reason?`<span>${esc(reason)}</span>`:''}</div><span>${currentRecs.length} ${currentRecs.length===1?'možnost':'možnosti'}</span></div>${currentRecs.map(productCard).join('')}`:''}
function bubble(t,who='bot',meta=''){if(!$('chatMessages'))return;const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=`<div>${String(t||'').replace(/\n/g,'<br>')}</div>${meta?`<small class="msg-meta">${esc(meta)}</small>`:''}`;$('chatMessages').appendChild(d);$('chatMessages').scrollTop=$('chatMessages').scrollHeight}
function typing(on){$('typing')?.classList.toggle('hidden',!on)}
function update(){if($('state'))$('state').textContent=`V11 · ${state.step} · ${state.intent||'brez kategorije'}${state.location?' · '+state.location:''}${state.safety?' · ⚠️ varnost':''}`;if($('debugPanel'))$('debugPanel').textContent=JSON.stringify({sessionId,...state},null,2)}
function chooseProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;state.selected=p;addToCart(id);showRecs([]);if(state.service&&state.location){state.step='lead';bubble(`Odlično. <b>${esc(p.name)}</b> sem dodal v košarico.<br><br>Imate tudi <b>${esc(state.service.toLowerCase())}</b> v kraju <b>${esc(state.location)}</b>. Lahko pripravim povpraševanje.`)}else{state.step='afterProduct';bubble(`Odlično. <b>${esc(p.name)}</b> je dodan v košarico.<br><br>Želite tudi pomoč električarja oziroma montažo?`)}update()}
function showDetail(id){const p=PRODUCTS.find(x=>x.id===id);if(!p||!$('productModal'))return;$('productModalBody').innerHTML=`<div class="detail-icon">${productIcon(p)}</div><div class="detail-copy"><span class="tag">${esc(p.category)}</span><h2>${esc(p.name)}</h2><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}${p.diameter?`<span>Ø ${esc(p.diameter)}</span>`:''}</div><p>${esc(p.desc||'')}</p><h3>Zakaj je lahko primeren?</h3><p>${p.category==='Svetila'?'Izdelek je izbran glede na trenutno zbrane podatke. Pri kopalnici je poleg IP treba preveriti tudi konkretno mesto in izvedbo.':p.category==='Zaščita'?'Zaščitni element mora biti izbran glede na konkreten tokokrog, vodnike, sistem in druge pogoje.':'Izdelek je predstavljen glede na lastnosti kataloga in namen, ki ste ga navedli.'}</p><button class="dark-btn" data-modal-add="${p.id}">Dodaj v košarico · ${eur(p.price)}</button></div>`;$('productModal').classList.remove('hidden')}
function closeDetail(){$('productModal')?.classList.add('hidden')}
async function aiSend(){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history,state,sessionId})});if(!r.ok)throw new Error('AI unavailable');return r.json()}
function showLead(){if($('leadBox'))$('leadBox').classList.remove('hidden');if($('leadLocation'))$('leadLocation').value=state.location||'';if($('leadNote'))$('leadNote').value=summary(state).join('\n');$('leadBox')?.scrollIntoView({behavior:'smooth',block:'center'})}
function prepareLead(){showLead();bubble(`<b>Povpraševanje je pripravljeno.</b><br><br>${summary(state).map(esc).join('<br>')}<br><br>Izpolnite kontaktne podatke in pošljite povpraševanje.`);update()}
async function submitLead(e){e.preventDefault();const btn=$('leadSubmit');btn.disabled=true;btn.textContent='Pošiljam …';const payload={name:$('leadName').value,email:$('leadEmail').value,phone:$('leadPhone').value,location:$('leadLocation')?.value||state.location||'',service:state.service||'',note:$('leadNote').value,summary:summary(state),sessionId};try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Napaka');$('leadResult').hidden=false;$('leadResult').innerHTML=`<b>✓ Povpraševanje poslano.</b><br>Številka: <strong>${esc(d.id)}</strong>`;state.step='completed';update();toast('Povpraševanje je sprejeto.')}catch(err){$('leadResult').hidden=false;$('leadResult').textContent=err.message||'Povpraševanja ni bilo mogoče poslati.'}finally{btn.disabled=false;btn.textContent='Pošlji povpraševanje'}}
async function send(text){text=text.trim();if(!text)return;bubble(esc(text),'user');history.push({role:'user',content:text});typing(true);if(['offer','lead','afterProduct'].includes(state.step)){const local=handleMessage(text,state);if(local.type==='selected'){typing(false);chooseProduct(local.product.id);return}if(local.type==='lead'){typing(false);prepareLead();return}if(local.type==='serviceAsk'){typing(false);bubble('Seveda. Za povpraševanje potrebujem še kontaktne podatke.');showLead();update();return}if(local.type==='done'){typing(false);bubble('V redu. Ko boste želeli, lahko nadaljujemo.');update();return}}
try{const ai=await aiSend();Object.assign(state,ai.statePatch||{});if(ai.safetyLevel==='electrician_required'){state.safety=true;state.safetyReason=state.safetyReason||'varnostno tveganje'}typing(false);if(ai.productIds?.length){showRecs(ai.productIds.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean),ai.reasoningSummary);state.step='offer'}else if(ai.statePatch?.step==='offer'){showRecs(recommend(state),ai.reasoningSummary);state.step='offer'}bubble(esc(ai.reply||'').replace(/\n/g,'<br>'),'bot',ai.safetyLevel==='electrician_required'?'Priporočljiv strokovni pregled':'AI svetovalec');history.push({role:'assistant',content:ai.reply||''});update()}catch(e){typing(false);const local=handleMessage(text,state);if(local.type==='question')bubble(esc(local.text));else if(local.type==='recommend'){bubble('Razumem. Na podlagi zbranih podatkov predlagam naslednje možnosti.');showRecs(local.products)}else if(local.type==='selected')chooseProduct(local.product.id);else if(local.type==='safety')bubble(esc(local.text));else if(local.type==='answer')bubble(esc(local.text));else if(local.type==='serviceLead'){state.step='lead';bubble(`Zabeležil sem potrebo po električarju v kraju <b>${esc(state.location)}</b>.<br><br>Pripravimo povpraševanje?`)}else bubble('AI trenutno ni dosegljiv. Opišite težavo še malo bolj konkretno in poskusil bom pomagati tudi lokalno.');update()}}
function reset(){state=freshState();history=[];currentRecs=[];if($('chatMessages'))$('chatMessages').innerHTML='';showRecs([]);if($('leadBox'))$('leadBox').classList.add('hidden');if($('leadResult')){$('leadResult').hidden=true;$('leadResult').textContent=''}bubble('Pozdravljeni! Sem <b>ElektroDom AI svetovalec</b>.<br>Opišite problem ali povejte, kaj potrebujete. Lahko napišete vse v enem stavku.');update()}
function startExample(t){if($('chatInput')){$('chatInput').value=t;$('chatInput').focus()}}
function renderProducts(){const grid=$('productGrid');if(!grid)return;const q=($('productSearch')?.value||'').toLowerCase().trim();const cat=$('productCategory')?.value||'';const data=PRODUCTS.filter(p=>(!q||`${p.name} ${p.category} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q))&&(!cat||p.category===cat));grid.innerHTML=data.map(p=>`<article class="product"><div class="product-icon">${productIcon(p)}</div><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><div class="chips">${p.ip?`<span>${esc(p.ip)}</span>`:''}${p.lumens?`<span>${esc(p.lumens)} lm</span>`:''}${p.colorTemp?`<span>${esc(p.colorTemp)}</span>`:''}</div><div class="product-bottom"><strong>${eur(p.price)}${p.unit?` / ${esc(p.unit)}`:''}</strong><button data-add="${p.id}">🛒</button></div><button class="product-link" data-detail="${p.id}">Podrobnosti →</button></article>`).join('')||'<p>Ni zadetkov.</p>'}
function renderHome(){const grid=$('homeProducts');if(!grid)return;grid.innerHTML=PRODUCTS.slice(0,5).map(p=>`<article class="product"><div class="product-icon">${productIcon(p)}</div><span class="tag">${p.id===1?'Top izbira':esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.ip||'Kakovostna rešitev')} · ${esc(p.colorTemp||'za dom')}</p><div class="product-bottom"><strong>${eur(p.price)}${p.unit?` / ${esc(p.unit)}`:''}</strong><button data-add="${p.id}">🛒</button></div><button class="product-link" data-detail="${p.id}">Podrobnosti →</button></article>`).join('')}
function setup(){document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){addToCart(+add.dataset.add);return}const choose=e.target.closest('[data-choose]');if(choose){chooseProduct(+choose.dataset.choose);return}const detail=e.target.closest('[data-detail]');if(detail){showDetail(+detail.dataset.detail);return}const rem=e.target.closest('[data-remove]');if(rem){removeCart(+rem.dataset.remove);return}const modalAdd=e.target.closest('[data-modal-add]');if(modalAdd){addToCart(+modalAdd.dataset.modalAdd);closeDetail();return}const filter=e.target.closest('[data-filter]');if(filter&&$('productCategory')){$('productCategory').value=filter.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));filter.classList.add('active');renderProducts()}});if($('chatForm'))$('chatForm').addEventListener('submit',e=>{e.preventDefault();const t=$('chatInput').value;$('chatInput').value='';send(t)});if($('resetChat'))$('resetChat').addEventListener('click',reset);if($('cartButton'))$('cartButton').addEventListener('click',openCart);if($('closeCart'))$('closeCart').addEventListener('click',closeCart);if($('closeProductModal'))$('closeProductModal').addEventListener('click',closeDetail);if($('productSearch'))$('productSearch').addEventListener('input',renderProducts);if($('productCategory'))$('productCategory').addEventListener('change',renderProducts);if($('leadForm'))$('leadForm').addEventListener('submit',submitLead);document.querySelectorAll('.example-btn').forEach(b=>b.addEventListener('click',()=>startExample(b.dataset.example)));if($('contactForm'))$('contactForm').addEventListener('submit',submitContact);renderCart();renderProducts();renderHome();const params=new URLSearchParams(location.search);if(params.get('cat')&&$('productCategory')){$('productCategory').value=params.get('cat');renderProducts()}if(params.get('debug')==='1')$('debugPanel')?.classList.remove('hidden');if($('chatMessages'))reset()}
async function submitContact(e){e.preventDefault();const btn=$('contactSubmit');btn.disabled=true;btn.textContent='Pošiljam …';const payload={name:$('contactName').value,email:$('contactEmail').value,phone:$('contactPhone').value,location:$('contactLocation').value,service:'Povpraševanje',note:$('contactNote').value,sessionId};try{const r=await fetch('/api/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Napaka');$('contactResult').hidden=false;$('contactResult').innerHTML=`<b>✓ Povpraševanje poslano.</b><br>Številka: <strong>${esc(d.id)}</strong>`;toast('Povpraševanje je sprejeto.')}catch(err){$('contactResult').hidden=false;$('contactResult').textContent=err.message||'Napaka pri pošiljanju.'}finally{btn.disabled=false;btn.textContent='Pošlji povpraševanje'}}
window.addToCart=addToCart;window.chooseProduct=chooseProduct;window.openCart=openCart;window.closeCart=closeCart;window.startExample=startExample;window.resetChat=reset;setup();
