import {PRODUCTS,freshState,handleMessage,summary,recommend} from './chat-engine.js';
const $=id=>document.getElementById(id), eur=n=>Number(n||0).toLocaleString('sl-SI',{style:'currency',currency:'EUR'});
let state=freshState(),cart=JSON.parse(localStorage.getItem('ed_cart')||'[]'),history=[];
function save(){localStorage.setItem('ed_cart',JSON.stringify(cart));}
function renderCart(){if($('cartCount'))$('cartCount').textContent=cart.length;if($('cartItems'))$('cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><span>${p.name}</span><b>${eur(p.price)}</b><button onclick="window.removeCart(${i})">×</button></div>`).join(''):'<p>Košarica je prazna.</p>';if($('cartTotal'))$('cartTotal').textContent=eur(cart.reduce((a,p)=>a+Number(p.price||0),0));}
function toast(t){if(!$('toast'))return;$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;cart.push(p);save();renderCart();toast(`${p.name} je dodan v košarico.`)}
function bubble(t,who='bot'){const d=document.createElement('div');d.className=`msg ${who}`;d.innerHTML=String(t||'').replace(/\n/g,'<br>');$('chatMessages').appendChild(d);$('chatMessages').scrollTop=$('chatMessages').scrollHeight}
function showRecs(ps){const list=(ps||[]).filter(Boolean).slice(0,3);$('recommendations').innerHTML=list.length?`<div class="rec-title">Priporočene možnosti</div>`+list.map((p,i)=>`<div class="rec"><div>${i+1}</div><div><b>${p.name}</b><small>${p.desc||''}${p.ip?` · ${p.ip}`:''}${p.lumens?` · ${p.lumens} lm`:''}${p.colorTemp?` · ${p.colorTemp}`:''}</small></div><strong>${eur(p.price)}</strong><button onclick="window.chooseProduct(${p.id})">Izberi</button></div>`).join(''):'';}
function update(){if($('state'))$('state').textContent=`V9 · ${state.step} · ${state.intent||'brez kategorije'}${state.location?' · '+state.location:''}${state.service?' · '+state.service:''}`}
function chooseProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;state.selected=p;cart.push(p);save();renderCart();$('recommendations').innerHTML='';if(state.service&&state.location){state.step='lead';bubble(`Odlično — <b>${p.name}</b> za <b>${eur(p.price)}</b> sem dodal v košarico.<br><br>Zabeležil sem tudi <b>${state.service.toLowerCase()}</b> v kraju <b>${state.location}</b>.<br><br>Želite, da pripravimo povpraševanje?`)}else{state.step='afterProduct';bubble(`Odlično — <b>${p.name}</b> za <b>${eur(p.price)}</b> sem dodal v košarico.<br><br>Želite tudi montažo oziroma pomoč električarja?`)}update()}
async function aiSend(text){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history,state})});if(!r.ok)throw new Error('AI unavailable');return r.json()}
async function send(text){text=text.trim();if(!text)return;bubble(text,'user');history.push({role:'user',content:text});
if(['offer','lead','afterProduct'].includes(state.step)){const local=handleMessage(text,state);if(local.type==='selected'){chooseProduct(local.product.id);return}if(local.type==='lead'){bubble(`<b>Povpraševanje je pripravljeno.</b><br><br>${summary(state).join('<br>')}<br><br><button class="inline-action" onclick="window.prepareLead()">Nadaljuj na povpraševanje</button>`);update();return}if(local.type==='serviceAsk'){bubble('Seveda. Za povpraševanje potrebujem še kraj in kontakt.');update();return}if(local.type==='done'){bubble('V redu. Ko boste želeli, lahko nadaljujemo.');update();return}}
try{const ai=await aiSend(text);Object.assign(state,ai.statePatch||{});if(ai.safetyLevel==='electrician_required')state.safety=true;if(ai.productIds?.length){const ps=ai.productIds.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean);showRecs(ps);state.step='offer';}else if(ai.statePatch?.step==='offer'){showRecs(recommend(state));state.step='offer';}bubble(ai.reply||'');history.push({role:'assistant',content:ai.reply||''});update();}
catch(e){const local=handleMessage(text,state);if(local.type==='question')bubble(local.text);else if(local.type==='recommend'){bubble('Razumem. Na podlagi zbranih podatkov predlagam naslednje možnosti.');showRecs(local.products)}else if(local.type==='selected')chooseProduct(local.product.id);else if(local.type==='serviceLead'){state.step='lead';bubble(`Zabeležil sem potrebo po električarju v kraju <b>${state.location}</b>.<br><br>Želite pripraviti povpraševanje?`)}else bubble('Trenutno sem brez povezave z AI. Opišite težavo še malo bolj konkretno in poskusil bom pomagati tudi lokalno.');update()}}
function prepareLead(){$('leadForm')?.scrollIntoView({behavior:'smooth',block:'center'});}
function reset(){state=freshState();history=[];if($('chatMessages'))$('chatMessages').innerHTML='';if($('recommendations'))$('recommendations').innerHTML='';bubble('Pozdravljeni! Sem <b>ElektroDom AI svetovalec</b>. Opišite, kaj potrebujete ali kakšno elektro težavo imate — lahko vse v enem stavku. Najprej bom razumel problem, nato preveril pomembne podatke in šele potem predlagal rešitev.');update()}
function startExample(t){$('chatInput').value=t;$('chatInput').focus()}
function openCart(){$('cartModal')?.classList.remove('hidden');renderCart()}function closeCart(){$('cartModal')?.classList.add('hidden')}function removeCart(i){cart.splice(i,1);save();renderCart()}
function renderProducts(){const grid=$('productGrid');if(!grid)return;const q=($('productSearch')?.value||'').toLowerCase();grid.innerHTML=PRODUCTS.filter(p=>!q||`${p.name} ${p.category} ${p.tags.join(' ')}`.toLowerCase().includes(q)).map(p=>`<article class="product"><div class="product-icon">${p.category==='Svetila'?'💡':p.category==='Vtičnice'?'🔌':p.category==='Zaščita'?'⚡':p.category==='Kabli'?'🧵':'▣'}</div><div class="tag">${p.category}</div><h3>${p.name}</h3><p>${p.desc}</p>${p.ip?`<span class="spec">${p.ip}</span>`:''}${p.lumens?`<span class="spec">${p.lumens} lm</span>`:''}${p.colorTemp?`<span class="spec">${p.colorTemp}</span>`:''}<div class="product-bottom"><strong>${eur(p.price)}${p.unit?` / ${p.unit}`:''}</strong><button onclick="window.addToCart(${p.id})">Dodaj</button></div></article>`).join('')||'<p>Ni zadetkov.</p>'}
function submitLead(e){e.preventDefault();if($('leadResult')){$('leadResult').hidden=false;$('leadResult').innerHTML='<b>Testno povpraševanje ustvarjeno.</b><br>V produkciji se lahko ta zapis pošlje v CRM, e-pošto ali bazo.'}}
window.addToCart=addToCart;window.chooseProduct=chooseProduct;window.removeCart=removeCart;window.openCart=openCart;window.closeCart=closeCart;window.startExample=startExample;window.resetChat=reset;window.prepareLead=prepareLead;
if($('chatForm'))$('chatForm').addEventListener('submit',e=>{e.preventDefault();const t=$('chatInput').value;$('chatInput').value='';send(t)});if($('resetChat'))$('resetChat').addEventListener('click',reset);if($('cartButton'))$('cartButton').addEventListener('click',openCart);if($('closeCart'))$('closeCart').addEventListener('click',closeCart);if($('productSearch'))$('productSearch').addEventListener('input',renderProducts);if($('leadForm'))$('leadForm').addEventListener('submit',submitLead);
renderCart();renderProducts();if($('chatMessages'))reset();
