let cart=[];let state={space:null,area:null,need:null,service:null,fixture:null,location:null};
const $=id=>document.getElementById(id),eur=n=>n.toLocaleString("sl-SI",{style:"currency",currency:"EUR"});
function addMessage(t,type){const d=document.createElement("div");d.className="msg "+type;d.innerHTML=t;$("chatMessages").appendChild(d);$("chatMessages").scrollTop=$("chatMessages").scrollHeight}
function openAssistant(){document.querySelector("#assistant").scrollIntoView({behavior:"smooth"});setTimeout(()=>$("chatInput").focus(),300)}
function quickAsk(t){$("chatInput").value=t;$("chatForm").requestSubmit()}
function resetChat(){state={space:null,area:null,need:null,service:null,fixture:null,location:null};$("chatMessages").innerHTML='<div class="msg bot">Nov pogovor. Opišite, kaj potrebujete.</div>';$("recommendations").innerHTML=""}
function area(t){let m=t.match(/(\d+(?:[.,]\d+)?)\s*(?:m2|m²)/i);return m?parseFloat(m[1].replace(",",".")):null}
function need(t){if(/električar|montaž|namestit|zmontir/i.test(t))return"service";if(/ne dela|izpad|iskra|varovalk|napak|pregorel/i.test(t))return"fault";if(/prenov|stanovanj|hiš|napeljav|material/i.test(t))return"project";if(/luč|svetil|plafonj|žarnic|led/i.test(t))return"lighting";if(/vtičnic|stikal/i.test(t))return"sockets";return null}
function recommend(){let list=[];if(state.need==="lighting")list=PRODUCTS.filter(p=>p.category==="Svetila").slice(0,3);else if(state.need==="sockets")list=PRODUCTS.filter(p=>["Vtičnice","Stikala"].includes(p.category)).slice(0,3);else if(state.need==="project")list=PRODUCTS.filter(p=>["Vtičnice","Stikala","Svetila"].includes(p.category)).slice(0,4);$("recommendations").innerHTML=list.length?'<div class="rec-title">Predlogi iz testnega kataloga</div>'+list.map(p=>`<div class="rec"><span>${p.icon}</span><div><b>${p.name}</b><small>${p.desc}</small><strong>${eur(p.price)}</strong></div><button onclick="addToCart(${p.id})">Dodaj</button></div>`).join(""):""}
function reply(text){let t=text.toLowerCase(),a=area(t),n=need(t);if(a)state.area=a;if(n)state.need=n;if(/kopalnic/i.test(t))state.space="kopalnica";if(/celj|celje/i.test(t))state.location="Celje";if(/maribor/i.test(t))state.location="Maribor";if(/ljubljan/i.test(t))state.location="Ljubljana";if(/tri|3\s*(?:svetilk|luči)/i.test(t))state.fixture=3;recommend();
if(state.need==="lighting"){if(state.space==="kopalnica"&&state.area)return`Razumem — iščete <b>svetilo za kopalnico velikosti ${state.area} m²</b>. Površine vam ni treba ponovno navajati. Pri kopalnici je pomembna ustrezna zaščita pred vlago in pravilna izbira glede na mesto namestitve.<br><br><b>Ali želite stropno ali stensko svetilo?</b><br>Če niste prepričani, vam lahko pokažem nekaj možnosti iz testnega kataloga.`;if(state.area)return`Super, zabeležil sem <b>${state.area} m²</b>. Ali iščete stropno, stensko ali drugo svetilo?`;return"Seveda. Za izbiro svetila potrebujem predvsem <b>prostor</b>, približno <b>površino</b> in mesto namestitve."}
if(state.need==="service")return`Razumem. Potrebujete električarja${state.fixture?` za približno <b>${state.fixture} svetilke</b>`:""}. Za pripravo povpraševanja potrebujem še <b>kraj</b> in kratek opis, ali je električna napeljava že pripravljena.<br><br>Če želite, lahko pripravite testno povpraševanje spodaj.`;
if(state.need==="fault")return"Pri električni napaki je varnost na prvem mestu. Ne bom ugibal o vzroku ali svetoval posegov v napeljavo na daljavo. Lahko pa pripravimo povpraševanje za električarja. Opišite <b>kaj ne deluje, kje je težava in ali je bilo iskrenje, dim ali vonj po zažganem</b>.";
if(state.need==="project")return"Razumem — gre za <b>projekt prenove</b>. Povejte približno površino, število prostorov in ali gre za novo ali delno napeljavo, pa lahko pripravimo začetni seznam materiala.";
if(state.need==="sockets")return"Lahko pomagam pri vtičnicah in stikalih. Povejte, ali potrebujete <b>novo montažo ali menjavo</b> in približno koliko kosov.";
return"Razumem. Povejte mi <b>kaj želite narediti, v katerem prostoru/objektu, približno velikost in ali potrebujete material, električarja ali oboje</b>."}
$("chatForm").addEventListener("submit",e=>{e.preventDefault();let i=$("chatInput"),t=i.value.trim();if(!t)return;addMessage(t,"user");i.value="";setTimeout(()=>addMessage(reply(t),"bot"),200)});
function render(filter=""){let q=filter.toLowerCase(),ps=PRODUCTS.filter(p=>(p.name+" "+p.category+" "+p.desc+" "+p.tags.join(" ")).toLowerCase().includes(q));$("productGrid").innerHTML=ps.map(p=>`<article><div class="pic">${p.icon}</div><small>${p.category}</small><h3>${p.name}</h3><p>${p.desc}</p><b class="price">${eur(p.price)}</b><button onclick="addToCart(${p.id})">Dodaj v košarico</button></article>`).join("")||"<p>Ni zadetkov.</p>"}
function addToCart(id){let p=PRODUCTS.find(x=>x.id===id);cart.push(p);$("cartCount").textContent=cart.length;toast(p.name+" je dodan v košarico.")}
function openCart(){$("cartModal").classList.remove("hidden");$("cartItems").innerHTML=cart.length?cart.map(p=>`<div class="row"><span>${p.name}</span><b>${eur(p.price)}</b></div>`).join(""):"<p>Košarica je prazna.</p>";$("cartTotal").textContent=eur(cart.reduce((s,p)=>s+p.price,0))}
function closeCart(){$("cartModal").classList.add("hidden")}function checkoutTest(){closeCart();toast("TEST: checkout bomo dodali v naslednji fazi.")}function toast(t){let e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function startService(s){$("serviceSelect").value=s;document.querySelector("#quote").scrollIntoView({behavior:"smooth"});$("description").focus()}
$("productSearch").addEventListener("input",e=>render(e.target.value));$("cartButton").addEventListener("click",openCart);
$("quoteForm").addEventListener("submit",e=>{e.preventDefault();let s=$("serviceSelect").value,c=$("city").value,p=$("phone").value,em=$("email").value,d=$("description").value,u=/nujno|takoj|danes|ne dela|iskra|dim|vonj po zažgan/i.test(d);$("quoteResult").style.display="block";$("quoteResult").innerHTML=`<b>TESTNI LEAD</b><br>Storitev: ${s}<br>Kraj: ${c}<br>Nujnost: <b>${u?"VISOKA":"OBIČAJNA"}</b><br>Telefon: ${p}<br>E-pošta: ${em||"ni podana"}<br><br><small>V2: podatki ostanejo samo v brskalniku. V produkciji bi lead šel v bazo/CRM.</small>`;$("leadPreview").innerHTML=`<b>Lead pripravljen</b><p>${s} • ${c} • ${u?"VISOKA":"OBIČAJNA"} nujnost</p>`});render();